export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const TRANSACTION_HISTORY = 'TRANSACTION_HISTORY'
export const TRANSACTION_DETAIL = 'TRANSACTION_DETAIL'
export const TRANSACTION_COMPLETE = 'TRANSACTION_COMPLETE'
export const TRANSACTION_CANCEL = 'TRANSACTION_CANCEL'
//Chi tiết các bước trong giao dịch mua/bán bất động sản
export const DEAL = 'DEAL'
export const LEGALITY = 'LEGALITY'
export const DEPOSIT = 'DEPOSIT'
export const CONTRACT = 'CONTRACT'
export const CONFIRMATION = 'CONFIRMATION'
export const TAX = 'TAX'
export const DELIVERY = 'DELIVERY'
export const TRANSFER = 'TRANSFER'
//Chi tiết các bước trong giao dịch cho thuê bất động sản
export const RENTING_DEAL = 'RENTING_DEAL'
export const RENTING_DEPOSIT = 'RENTING_DEPOSIT'
export const RENTING_CONTRACT = 'RENTING_CONTRACT'
export const RENTING_CONFIRMATION = 'RENTING_CONFIRMATION'
export const RENTING_DELIVERY = 'RENTING_DELIVERY'
