export const FETCH_ESTATES_AROUND_CURRENT_LOCATION = 'FETCH_ESTATES_AROUND_CURRENT_LOCATION';
export const GET_INFO_ESTATE = 'GET_INFO_ESTATE';
export const GET_LIST_ESTATE_FROM_FORM_SEARCH = 'GET_LIST_ESTATE_FROM_FORM_SEARCH'
export const SAVE_INFO_USER = 'SAVE_INFO_USER';
export const GET_NEWS_BY_TYPE = 'GET_NEWS_BY_TYPE';
export const GET_NEWS_BY_ID = 'GET_NEWS_BY_ID'
export const DELETE_PROJECT = 'DELETE_PROJECT'
//========Map===========
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const SAVE_LOCATION_INFO = 'SAVE_LOCATION_INFO'
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'
export const POST_COMMENT = 'POST_COMMENT'
export const GET_ESTATE_LIST_OF_USER = 'GET_ESTATE_LIST_OF_USER'
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT'
