export const SAVE_FOLLOW_PROJECTID = 'SAVE_FOLLOW_PROJECTID'
export const GET_FOLLOWING_LIST = 'GET_FOLLOWING_LIST'
export const UNFOLLOW_PROJECT = 'UNFOLLOW_PROJECT'
export const FOLLOW_PROJECT = 'FOLLOW_PROJECT'