export const GET_INFO_EMPLOYEE = 'GET_INFO_EMPLOYEE';
export const GET_LIST_PROJECT_OF_EMPLOYEE = 'GET_LIST_PROJECT_OF_EMPLOYEE';
export const EDIT_EMPLOYEE_PROJECT = 'EDIT_EMPLOYEE_PROJECT'
export const DELETE_EMPLOYEE_PROJECT = 'DELETE_EMPLOYEE_PROJECT'