export const PROFILE = 'PROFILE';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const LIST_EMPLOYEES = 'LIST_EMPLOYEES'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const MY_TRANSACTION = 'MY_TRANSACTION'
export const MY_TRANSACTION_HISTORY = ' MY_TRANSACTION_HISTORY'